# Test generated by RoostGPT for test PythonUnitTest using AI Type Open AI and AI Model gpt-4

import unittest

def display_word(word, guessed_letters):
    display = ""
    for letter in word:
        if letter in guessed_letters:
            display += letter
        else:
            display += "_"
    return display

class TestDisplayWord(unittest.TestCase):
    def test_display_word_success(self):
        result = display_word("apple", ["a", "p"])
        self.assertEqual(result, "app__")

    def test_display_word_failure(self):
        result = display_word("apple", ["b", "c"])
        self.assertEqual(result, "_____")

    def test_display_word_edge_case(self):
        result = display_word("", ["a", "p"])
        self.assertEqual(result, "")

    def test_display_word_error_handling(self):
        with self.assertRaises(TypeError):
            display_word("apple", 123)

if __name__ == '__main__':
    unittest.main()
