# Test generated by RoostGPT for test PythonUnitTest using AI Type Open AI and AI Model gpt-4

import unittest
import random

def choose_random_word():
    words = ["apple", "banana", "cherry", "grape",
             "orange", "watermelon", "kiwi", "mango"]
    return random.choice(words)

class TestChoose_random_word_dfc5b1b036(unittest.TestCase):

    def test_choose_random_word(self):
        word = choose_random_word()
        self.assertIn(word, ["apple", "banana", "cherry", "grape",
                             "orange", "watermelon", "kiwi", "mango"])

    def test_choose_random_word_failure(self):
        word = choose_random_word()
        self.assertNotIn(word, ["pineapple", "strawberry", "blueberry"])

if __name__ == '__main__':
    unittest.main()
